export 'package:segadi/view/home/login.dart';
export 'package:segadi/view/services/services_operator.dart';
export 'package:segadi/view/home/home.dart';
export 'package:segadi/view/services/detail_service.dart';
export 'package:segadi/view/services/detail_finished.dart';
export 'package:segadi/view/services/finished_services.dart';
export 'package:segadi/view/services/check_list.dart';
export 'package:segadi/view/services/status_support.dart';
export 'package:segadi/view/services/trip_closure.dart';
