// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2b5AKGs40n5sACB3fzFHGhmSROXKbzsc',
    appId: '1:681562092676:web:2bc18a5420daaa9086fed1',
    messagingSenderId: '681562092676',
    projectId: 'segadi-app',
    authDomain: 'segadi-app.firebaseapp.com',
    storageBucket: 'segadi-app.firebasestorage.app',
    measurementId: 'G-DCBKWKZER6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkJs4DCUDNbkyPxtt2shT4CklLe4jGP6c',
    appId: '1:681562092676:android:1c62839e8209c13686fed1',
    messagingSenderId: '681562092676',
    projectId: 'segadi-app',
    storageBucket: 'segadi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-QSSQGHQ2g3iNZpNEp3BcAX4m2Sz_2s',
    appId: '1:681562092676:ios:8795eaf061a4035686fed1',
    messagingSenderId: '681562092676',
    projectId: 'segadi-app',
    storageBucket: 'segadi-app.firebasestorage.app',
    iosBundleId: 'com.example.segadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-QSSQGHQ2g3iNZpNEp3BcAX4m2Sz_2s',
    appId: '1:681562092676:ios:8795eaf061a4035686fed1',
    messagingSenderId: '681562092676',
    projectId: 'segadi-app',
    storageBucket: 'segadi-app.firebasestorage.app',
    iosBundleId: 'com.example.segadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2b5AKGs40n5sACB3fzFHGhmSROXKbzsc',
    appId: '1:681562092676:web:59fb430cd7f62ccf86fed1',
    messagingSenderId: '681562092676',
    projectId: 'segadi-app',
    authDomain: 'segadi-app.firebaseapp.com',
    storageBucket: 'segadi-app.firebasestorage.app',
    measurementId: 'G-Q9J2HRQJR2',
  );
}
